-- Slim schema: deixa apenas as colunas que o dashboard usa.
-- Reduz volume de carga, simplifica ETL e remove ambiguidade.

drop table if exists "2026_ppb1".resultados_turmas cascade;

create table "2026_ppb1".resultados_turmas (
  id bigint generated by default as identity primary key,
  ure text not null,
  escola text not null,
  turma text not null,
  bimestre int,
  tipo_prova text,
  dia_prova int not null,                      -- 1 ou 2
  serie text,                                  -- derivada no ETL (4EF..3EM)
  total_alunos_turma int,                      -- denominador
  gabaritos_lidos_cmspp int,                   -- numerador
  atualizacao timestamptz,
  escola_id text generated always as (md5(ure || '|' || escola)) stored,
  turma_id text generated always as (md5(ure || '|' || escola || '|' || turma)) stored
);

create index idx_ppb1_ure on "2026_ppb1".resultados_turmas (ure);
create index idx_ppb1_escola_id on "2026_ppb1".resultados_turmas (escola_id);
create index idx_ppb1_turma_id on "2026_ppb1".resultados_turmas (turma_id);
create index idx_ppb1_serie on "2026_ppb1".resultados_turmas (serie);
create index idx_ppb1_bim_tipo_dia on "2026_ppb1".resultados_turmas (bimestre, tipo_prova, dia_prova);

-- Deduplicação garantida no banco (proteção a mais além do que o ETL valida)
create unique index uq_ppb1_turma_dia on "2026_ppb1".resultados_turmas (turma_id, dia_prova);

grant usage on schema "2026_ppb1" to anon, authenticated, service_role;
grant all privileges on all tables in schema "2026_ppb1" to service_role;
grant select on all tables in schema "2026_ppb1" to anon, authenticated;
alter default privileges in schema "2026_ppb1" grant all on tables to service_role;
alter default privileges in schema "2026_ppb1" grant select on tables to anon, authenticated;

alter table "2026_ppb1".resultados_turmas enable row level security;
drop policy if exists "leitura_publica" on "2026_ppb1".resultados_turmas;
create policy "leitura_publica" on "2026_ppb1".resultados_turmas
  for select to anon, authenticated using (true);
