-- Schema Prova Paulista Bimestre 1 / 2026
create schema if not exists "2026_ppb1";

create table if not exists "2026_ppb1"."resultados_turmas" (
  id bigint generated by default as identity primary key,
  ure text,
  municipio text,
  escola text,
  turma text,
  ano_prova integer,
  bimestre integer,
  tipo_prova text,
  dia_prova integer,
  nome_prova_roxo text,
  nome_prova_laranja text,
  nome_prova_verde text,
  nome_prova_amarela text,
  id_publicacao_roxo bigint,
  id_publicacao_laranja bigint,
  id_publicacao_verde bigint,
  id_publicacao_amarela bigint,
  id_modelo_roxo bigint,
  id_modelo_laranja bigint,
  id_modelo_verde bigint,
  id_modelo_amarela bigint,
  qtd_envios_iptv_roxo integer,
  qtd_envios_iptv_laranja integer,
  qtd_envios_iptv_verde integer,
  qtd_envios_iptv_amarela integer,
  qtd_gabaritos_roxo integer,
  qtd_gabaritos_laranja integer,
  qtd_gabaritos_verde integer,
  qtd_gabaritos_amarela integer,
  data_vigencia_publicacao date,
  data_inicio_agendamento date,
  data_fim_agendamento date,
  total_alunos_turma integer,
  gabaritos_lidos_cmspp integer,
  total_gabaritos_enviados_iptv integer,
  perc_gabaritos_lidos integer,
  atualizacao timestamptz,
  escola_id text generated always as (
    md5(coalesce(ure,'') || '|' || coalesce(escola,''))
  ) stored,
  turma_id text generated always as (
    md5(coalesce(ure,'') || '|' || coalesce(escola,'') || '|' || coalesce(turma,''))
  ) stored
);

create index if not exists idx_ppb1_ure on "2026_ppb1"."resultados_turmas" (ure);
create index if not exists idx_ppb1_escola_id on "2026_ppb1"."resultados_turmas" (escola_id);
create index if not exists idx_ppb1_turma_id on "2026_ppb1"."resultados_turmas" (turma_id);
create index if not exists idx_ppb1_bim_tipo_dia on "2026_ppb1"."resultados_turmas" (bimestre, tipo_prova, dia_prova);

-- Privilégios
grant usage on schema "2026_ppb1" to anon, authenticated, service_role;
grant all privileges on all tables in schema "2026_ppb1" to service_role;
grant select on all tables in schema "2026_ppb1" to anon, authenticated;
alter default privileges in schema "2026_ppb1" grant all on tables to service_role;
alter default privileges in schema "2026_ppb1" grant select on tables to anon, authenticated;

-- RLS
alter table "2026_ppb1"."resultados_turmas" enable row level security;
drop policy if exists "leitura_publica" on "2026_ppb1"."resultados_turmas";
create policy "leitura_publica" on "2026_ppb1"."resultados_turmas"
  for select to anon, authenticated using (true);

-- ==========================================================================
-- RPCs no schema public (security definer) — consumidas pelo frontend
-- ==========================================================================

create or replace function public.ppb1_get_available_filters()
returns table (bimestres int[], tipos_prova text[])
language sql stable security definer set search_path = public
as $$
  select
    array_agg(distinct bimestre order by bimestre) filter (where bimestre is not null),
    array_agg(distinct tipo_prova order by tipo_prova) filter (where tipo_prova is not null)
  from "2026_ppb1"."resultados_turmas";
$$;

create or replace function public.ppb1_get_summary_cards(
  p_bimestre int,
  p_tipo_prova text
)
returns table (
  total_alunos_dia1 bigint,
  total_alunos_dia2 bigint,
  total_lidos_dia1 bigint,
  total_lidos_dia2 bigint,
  perc_dia1 numeric,
  perc_dia2 numeric
)
language sql stable security definer set search_path = public
as $$
  with base as (
    select dia_prova,
           coalesce(total_alunos_turma,0) as alunos,
           coalesce(gabaritos_lidos_cmspp,0) as lidos
    from "2026_ppb1"."resultados_turmas"
    where bimestre = p_bimestre and tipo_prova = p_tipo_prova
  )
  select
    sum(alunos) filter (where dia_prova=1)::bigint,
    sum(alunos) filter (where dia_prova=2)::bigint,
    sum(lidos)  filter (where dia_prova=1)::bigint,
    sum(lidos)  filter (where dia_prova=2)::bigint,
    case when sum(alunos) filter (where dia_prova=1) > 0
         then round(100.0 * sum(lidos) filter (where dia_prova=1)
                    / sum(alunos) filter (where dia_prova=1), 2)
         else 0 end,
    case when sum(alunos) filter (where dia_prova=2) > 0
         then round(100.0 * sum(lidos) filter (where dia_prova=2)
                    / sum(alunos) filter (where dia_prova=2), 2)
         else 0 end
  from base;
$$;

create or replace function public.ppb1_get_seduc_table(
  p_bimestre int,
  p_tipo_prova text
)
returns table (
  ure text,
  total_escolas bigint,
  total_turmas bigint,
  total_alunos bigint,
  perc_dia1 numeric,
  perc_dia2 numeric
)
language sql stable security definer set search_path = public
as $$
  select
    t.ure,
    count(distinct t.escola_id)::bigint,
    count(distinct t.turma_id)::bigint,
    sum(coalesce(t.total_alunos_turma,0)) filter (where t.dia_prova=1)::bigint,
    case when sum(coalesce(t.total_alunos_turma,0)) filter (where t.dia_prova=1) > 0
         then round(100.0 * sum(coalesce(t.gabaritos_lidos_cmspp,0)) filter (where t.dia_prova=1)
                    / sum(coalesce(t.total_alunos_turma,0)) filter (where t.dia_prova=1), 2)
         else 0 end,
    case when sum(coalesce(t.total_alunos_turma,0)) filter (where t.dia_prova=2) > 0
         then round(100.0 * sum(coalesce(t.gabaritos_lidos_cmspp,0)) filter (where t.dia_prova=2)
                    / sum(coalesce(t.total_alunos_turma,0)) filter (where t.dia_prova=2), 2)
         else 0 end
  from "2026_ppb1"."resultados_turmas" t
  where t.bimestre = p_bimestre and t.tipo_prova = p_tipo_prova and t.ure is not null
  group by t.ure
  order by t.ure;
$$;

create or replace function public.ppb1_get_ure_table(
  p_bimestre int,
  p_tipo_prova text,
  p_ure text
)
returns table (
  escola_id text,
  escola text,
  total_turmas bigint,
  total_alunos bigint,
  perc_dia1 numeric,
  perc_dia2 numeric
)
language sql stable security definer set search_path = public
as $$
  select
    t.escola_id,
    max(t.escola) as escola,
    count(distinct t.turma_id)::bigint,
    sum(coalesce(t.total_alunos_turma,0)) filter (where t.dia_prova=1)::bigint,
    case when sum(coalesce(t.total_alunos_turma,0)) filter (where t.dia_prova=1) > 0
         then round(100.0 * sum(coalesce(t.gabaritos_lidos_cmspp,0)) filter (where t.dia_prova=1)
                    / sum(coalesce(t.total_alunos_turma,0)) filter (where t.dia_prova=1), 2)
         else 0 end,
    case when sum(coalesce(t.total_alunos_turma,0)) filter (where t.dia_prova=2) > 0
         then round(100.0 * sum(coalesce(t.gabaritos_lidos_cmspp,0)) filter (where t.dia_prova=2)
                    / sum(coalesce(t.total_alunos_turma,0)) filter (where t.dia_prova=2), 2)
         else 0 end
  from "2026_ppb1"."resultados_turmas" t
  where t.bimestre = p_bimestre
    and t.tipo_prova = p_tipo_prova
    and t.ure = p_ure
    and t.escola is not null
  group by t.escola_id
  order by max(t.escola);
$$;

create or replace function public.ppb1_get_escola_table(
  p_bimestre int,
  p_tipo_prova text,
  p_escola_id text
)
returns table (
  turma_id text,
  turma text,
  total_alunos bigint,
  perc_dia1 numeric,
  perc_dia2 numeric
)
language sql stable security definer set search_path = public
as $$
  select
    t.turma_id,
    max(t.turma) as turma,
    sum(coalesce(t.total_alunos_turma,0)) filter (where t.dia_prova=1)::bigint,
    case when sum(coalesce(t.total_alunos_turma,0)) filter (where t.dia_prova=1) > 0
         then round(100.0 * sum(coalesce(t.gabaritos_lidos_cmspp,0)) filter (where t.dia_prova=1)
                    / sum(coalesce(t.total_alunos_turma,0)) filter (where t.dia_prova=1), 2)
         else 0 end,
    case when sum(coalesce(t.total_alunos_turma,0)) filter (where t.dia_prova=2) > 0
         then round(100.0 * sum(coalesce(t.gabaritos_lidos_cmspp,0)) filter (where t.dia_prova=2)
                    / sum(coalesce(t.total_alunos_turma,0)) filter (where t.dia_prova=2), 2)
         else 0 end
  from "2026_ppb1"."resultados_turmas" t
  where t.bimestre = p_bimestre
    and t.tipo_prova = p_tipo_prova
    and t.escola_id = p_escola_id
    and t.turma is not null
  group by t.turma_id
  order by max(t.turma);
$$;

create or replace function public.ppb1_get_ure_list(
  p_bimestre int,
  p_tipo_prova text
)
returns table (ure text)
language sql stable security definer set search_path = public
as $$
  select distinct t.ure
  from "2026_ppb1"."resultados_turmas" t
  where t.bimestre = p_bimestre and t.tipo_prova = p_tipo_prova and t.ure is not null
  order by t.ure;
$$;

create or replace function public.ppb1_get_escola_list(
  p_bimestre int,
  p_tipo_prova text,
  p_ure text
)
returns table (escola_id text, escola text)
language sql stable security definer set search_path = public
as $$
  select distinct t.escola_id, t.escola
  from "2026_ppb1"."resultados_turmas" t
  where t.bimestre = p_bimestre
    and t.tipo_prova = p_tipo_prova
    and t.ure = p_ure
    and t.escola is not null
  order by t.escola;
$$;

grant execute on function public.ppb1_get_available_filters() to anon, authenticated;
grant execute on function public.ppb1_get_summary_cards(int,text) to anon, authenticated;
grant execute on function public.ppb1_get_seduc_table(int,text) to anon, authenticated;
grant execute on function public.ppb1_get_ure_table(int,text,text) to anon, authenticated;
grant execute on function public.ppb1_get_escola_table(int,text,text) to anon, authenticated;
grant execute on function public.ppb1_get_ure_list(int,text) to anon, authenticated;
grant execute on function public.ppb1_get_escola_list(int,text,text) to anon, authenticated;
